// <auto-generated />
using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace CryptoTracker.Models
{

    public class Trending
    {
        public Coin[] coins { get; set; }
        public object[] exchanges { get; set; }
    }

    public class Coin
    {
        public Item item { get; set; }
    }

    public class Item
    {
        public string id { get; set; }
        public int coin_id { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public int market_cap_rank { get; set; }
        public string thumb { get; set; }
        public string small { get; set; }
        public string large { get; set; }
        public string slug { get; set; }
        public float price_btc { get; set; }
        public int score { get; set; }
    }

}
